---
version: 2
plan:
  project-key: MYPRJ
  name: First RUN
  key: RUN1
triggers:
  - polling: 3
stages:
  - First Build Stage:
      jobs: 
        - Build Step
  - Second Build Stage:
      jobs:
        - Build1 Step
        - Test Step

Build Step:
  tasks:
    - script:
        - echo 'Hello world'
        - docker ps -a
Build1 Step:
  tasks:
    - script:
        - echo 'Hello my world'
        - docker ps        
Test Step:
  tasks:
    - script:
        - echo 'Hello world test'
        - ls -la
        - echo "Test test"